### ISSUE TITLE
漏洞：连锁挖掘红石矿时不工作

### ISSUE THREAD

**Issue by HamdsomeAtom125** [SourceLandDev/Scripts#1]
### 操作系统

Android

### Minecraft版本

1.20.31.01

### 描述漏洞

开启连锁挖掘后，使用镐子挖掘红石矿时，连锁挖掘会失效。
这可能是因为挖掘时会激活红石矿，此时激活的矿石和未激活的矿石是两种状态，导致连锁挖掘失效。

### 重现步骤

挖掘红石矿

### 预期行为

在开启连锁挖矿后，将红石矿群连锁挖掘

**Comment by Hosiyume** [comment]
已修复，请确认无问题后关闭issue

**Comment by HamdsomeAtom125** [comment]
仍旧存在问题。

测试物品：深层红石矿石（minecraft:deepslate_redstone_ore）
挖掘后仍旧无法做到连锁采集。

**Comment by Hosiyume** [comment]
已修复

**Comment by Hosiyume** [comment]
过时可能

**Comment by HamdsomeAtom125** [comment]
今天中午12:30将再次测试

**Comment by HamdsomeAtom125** [comment]
忘了close issue了 十分抱歉
已经测试过挖掘红石 问题已解决
